sudo: required
services:
  - docker

before_install:
  - docker build -t pureomega/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pureomega/react-test npm test -- --coverage
#AFTER SUCCESS
after_success:
  - docker build -t pureomega/complex-client ./client
  - docker build -t pureomega/complex-nginx ./nginx
  - docker build -t pureomega/complex-server ./server
  - docker build -t pureomega/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pureomega/complex-client
  - docker push pureomega/complex-nginx
  - docker push pureomega/complex-server
  - docker push pureomega/complex-worker
